### ISSUE TITLE
In fact, this kernel image can not work on nougat...

### ISSUE THREAD

**Issue by GuaiYiHu** [javichampi/miui8_kernel_extracted_mi2#1]
Good luck for your work.

**Comment by javichampi** [comment]
Yes I realize this won't be useful in nougat, but I wanted to see inside the ramdisk to compare some files. I'm mad with the booting process of the ROM.

**Comment by GuaiYiHu** [comment]
I made it.
https://github.com/aries-dev-playground/android_kernel_xiaomi_msm8960/tree/cm-14.1

**Comment by javichampi** [comment]
Oh fine, I saw your progress last month while I'm on holidays. Is your ROM booting??

**Comment by GuaiYiHu** [comment]
yup

**Comment by javichampi** [comment]
OK i will use your sources for testing. Have you take a look to this work?: [https://github.com/Unlegacy-Android](url) They are working on legacy devices to make AOSP roms updated (mako is one of them)

**Comment by GuaiYiHu** [comment]
No, I will bring up O for aries then. I do not have the ability to fix bugs. Just make it bootable.
